import { Tool } from '@/types/tool';

/**
 * All PDF and Image tools configuration
 * Core tools: PDF to Word, Word to PDF, Image to PDF, Merge PDF, Compress PDF
 * Advanced tools: PDF to PPT, PPT to PDF, PDF to Excel, Excel to PDF, Split PDF,
 *                 Reorder PDF, Rotate PDF, Protect PDF, Unlock PDF, Watermark PDF,
 *                 Sign PDF, Edit PDF
 * Image tools: Resize, Crop/Rotate, Compress, Convert, Photo Editor, Text/Sticker,
 *              Background Remove, Upscale, Passport Photo
 */
export const TOOLS: Tool[] = [
  // Core Tools
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    slug: 'pdf-to-word',
    description: 'Convert PDF documents to editable Word files while preserving formatting and layout.',
    shortDescription: 'PDF to DOCX',
    icon: 'file-word',
    category: 'core',
    acceptedFormats: ['.pdf'],
    outputFormat: '.docx',
    maxFileSize: 50 * 1024 * 1024, // 50MB
    maxFiles: 1,
    processingLocation: 'server',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    slug: 'word-to-pdf',
    description: 'Convert Word documents to PDF format with perfect formatting preservation.',
    shortDescription: 'DOCX to PDF',
    icon: 'file-pdf',
    category: 'core',
    acceptedFormats: ['.docx', '.doc'],
    outputFormat: '.pdf',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'server',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    slug: 'image-to-pdf',
    description: 'Convert JPG and PNG images to PDF documents quickly and easily.',
    shortDescription: 'JPG/PNG to PDF',
    icon: 'image',
    category: 'core',
    acceptedFormats: ['.jpg', '.jpeg', '.png'],
    outputFormat: '.pdf',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 20,
    processingLocation: 'client',
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    slug: 'merge-pdf',
    description: 'Combine multiple PDF files into a single document with custom page order.',
    shortDescription: 'Combine PDFs',
    icon: 'files',
    category: 'core',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 20,
    processingLocation: 'client',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    slug: 'compress-pdf',
    description: 'Reduce PDF file size while maintaining acceptable quality for sharing.',
    shortDescription: 'Reduce PDF size',
    icon: 'compress',
    category: 'core',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 100 * 1024 * 1024, // 100MB for compression
    maxFiles: 1,
    processingLocation: 'client',
  },

  // Advanced Tools
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PowerPoint',
    slug: 'pdf-to-ppt',
    description: 'Convert PDF files to editable PowerPoint presentations.',
    shortDescription: 'PDF to PPTX',
    icon: 'presentation',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pptx',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'server',
  },
  {
    id: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    slug: 'ppt-to-pdf',
    description: 'Convert PowerPoint presentations to PDF format.',
    shortDescription: 'PPTX to PDF',
    icon: 'file-pdf',
    category: 'advanced',
    acceptedFormats: ['.pptx', '.ppt'],
    outputFormat: '.pdf',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'server',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    slug: 'pdf-to-excel',
    description: 'Extract tables from PDF documents and convert them to Excel spreadsheets.',
    shortDescription: 'PDF to XLSX',
    icon: 'table',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.xlsx',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'server',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    slug: 'excel-to-pdf',
    description: 'Convert Excel spreadsheets to PDF format with proper formatting.',
    shortDescription: 'XLSX to PDF',
    icon: 'file-pdf',
    category: 'advanced',
    acceptedFormats: ['.xlsx', '.xls'],
    outputFormat: '.pdf',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'server',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    slug: 'split-pdf',
    description: 'Divide a PDF into separate pages or extract specific page ranges.',
    shortDescription: 'Extract pages',
    icon: 'scissors',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'reorder-pdf',
    name: 'Reorder PDF',
    slug: 'reorder-pdf',
    description: 'Rearrange PDF pages in any order using drag-and-drop.',
    shortDescription: 'Rearrange pages',
    icon: 'sort',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    slug: 'rotate-pdf',
    description: 'Rotate PDF pages by 90, 180, or 270 degrees.',
    shortDescription: 'Rotate pages',
    icon: 'rotate',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    slug: 'protect-pdf',
    description: 'Add password protection to secure your PDF documents.',
    shortDescription: 'Add password',
    icon: 'lock',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    slug: 'unlock-pdf',
    description: 'Remove password protection from PDF files with valid credentials.',
    shortDescription: 'Remove password',
    icon: 'unlock',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    slug: 'watermark-pdf',
    description: 'Add text or image watermarks to your PDF pages.',
    shortDescription: 'Add watermark',
    icon: 'droplet',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    slug: 'sign-pdf',
    description: 'Draw or upload your signature and place it on PDF documents.',
    shortDescription: 'Add signature',
    icon: 'pen',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    slug: 'edit-pdf',
    description: 'Add text, highlight, and draw on your PDF documents.',
    shortDescription: 'Edit & annotate',
    icon: 'edit',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    slug: 'ocr-pdf',
    description: 'Extract text from scanned PDFs and images using optical character recognition.',
    shortDescription: 'Extract text',
    icon: 'eye',
    category: 'advanced',
    acceptedFormats: ['.pdf', '.jpg', '.jpeg', '.png'],
    outputFormat: '.pdf',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'server',
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    slug: 'repair-pdf',
    description: 'Fix corrupted or damaged PDF files and recover content.',
    shortDescription: 'Fix corrupted PDFs',
    icon: 'wrench',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'compare-pdf',
    name: 'Compare PDF',
    slug: 'compare-pdf',
    description: 'Compare two PDF documents and highlight the differences between them.',
    shortDescription: 'Find differences',
    icon: 'search',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 2,
    processingLocation: 'client',
  },
  {
    id: 'scan-to-pdf',
    name: 'Scan to PDF',
    slug: 'scan-to-pdf',
    description: 'Scan documents using your camera and convert them to PDF format.',
    shortDescription: 'Scan documents',
    icon: 'camera',
    category: 'advanced',
    acceptedFormats: ['.jpg', '.jpeg', '.png'],
    outputFormat: '.pdf',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 20,
    processingLocation: 'client',
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    slug: 'crop-pdf',
    description: 'Crop PDF pages to remove unwanted margins or resize page dimensions.',
    shortDescription: 'Crop pages',
    icon: 'crop',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    slug: 'page-numbers',
    description: 'Add page numbers to your PDF documents with customizable position and format.',
    shortDescription: 'Add page numbers',
    icon: 'hash',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    slug: 'redact-pdf',
    description: 'Permanently remove sensitive information from PDF documents.',
    shortDescription: 'Hide sensitive info',
    icon: 'shield',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    slug: 'pdf-to-pdfa',
    description: 'Convert PDF to PDF/A format for long-term archiving and preservation.',
    shortDescription: 'Archive format',
    icon: 'archive',
    category: 'advanced',
    acceptedFormats: ['.pdf'],
    outputFormat: '.pdf',
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'server',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    slug: 'html-to-pdf',
    description: 'Convert web pages and HTML content to PDF documents.',
    shortDescription: 'Web to PDF',
    icon: 'globe',
    category: 'advanced',
    acceptedFormats: ['.html', '.htm'],
    outputFormat: '.pdf',
    maxFileSize: 10 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'server',
  },

  // Image Tools
  {
    id: 'resize-image',
    name: 'Resize Image',
    slug: 'resize-image',
    description: 'Resize images to specific dimensions with presets for social media and documents.',
    shortDescription: 'Resize to any size',
    icon: 'resize',
    category: 'image',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'same',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 20,
    processingLocation: 'client',
  },
  {
    id: 'crop-rotate-image',
    name: 'Crop & Rotate Image',
    slug: 'crop-rotate-image',
    description: 'Crop, rotate, and flip images with preset aspect ratios and straighten tools.',
    shortDescription: 'Crop & rotate',
    icon: 'crop',
    category: 'image',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'same',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'compress-image',
    name: 'Compress Image',
    slug: 'compress-image',
    description: 'Reduce image file size while maintaining quality for web and sharing.',
    shortDescription: 'Reduce file size',
    icon: 'compress',
    category: 'image',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'same',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 20,
    processingLocation: 'client',
  },
  {
    id: 'convert-image',
    name: 'Convert Image',
    slug: 'convert-image',
    description: 'Convert images between JPG, PNG, and WEBP formats with quality options.',
    shortDescription: 'Change format',
    icon: 'convert',
    category: 'image',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.heic'],
    outputFormat: 'multiple',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 20,
    processingLocation: 'client',
  },
  {
    id: 'photo-editor',
    name: 'Photo Editor',
    slug: 'photo-editor',
    description: 'Adjust brightness, contrast, saturation, and apply filters to enhance photos.',
    shortDescription: 'Edit & enhance',
    icon: 'edit',
    category: 'image',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'same',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'add-text-sticker',
    name: 'Text & Stickers',
    slug: 'add-text-sticker',
    description: 'Add text, emojis, and stickers to images with customizable fonts and styles.',
    shortDescription: 'Add text & stickers',
    icon: 'text',
    category: 'image',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'same',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'remove-background',
    name: 'Remove Background',
    slug: 'remove-background',
    description: 'AI-powered background removal with options for transparent, solid, or custom backgrounds.',
    shortDescription: 'Remove BG',
    icon: 'background',
    category: 'image',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: '.png',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'upscale-image',
    name: 'Upscale Image',
    slug: 'upscale-image',
    description: 'AI-powered image upscaling to enhance resolution by 2x or 4x.',
    shortDescription: 'Enhance resolution',
    icon: 'upscale',
    category: 'image',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'same',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
  {
    id: 'passport-photo',
    name: 'Passport Photo',
    slug: 'passport-photo',
    description: 'Create passport-compliant photos with auto face detection and background replacement.',
    shortDescription: 'ID photos',
    icon: 'passport',
    category: 'image',
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: '.jpg',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    processingLocation: 'client',
  },
];

/**
 * Get a tool by its slug
 */
export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find((tool) => tool.slug === slug);
}

/**
 * Get a tool by its ID
 */
export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((tool) => tool.id === id);
}

/**
 * Get all tools by category
 */
export function getToolsByCategory(category: 'core' | 'advanced' | 'image'): Tool[] {
  return TOOLS.filter((tool) => tool.category === category);
}

/**
 * Get core tools
 */
export function getCoreTools(): Tool[] {
  return getToolsByCategory('core');
}

/**
 * Get advanced tools
 */
export function getAdvancedTools(): Tool[] {
  return getToolsByCategory('advanced');
}

/**
 * Get image tools
 */
export function getImageTools(): Tool[] {
  return getToolsByCategory('image');
}
